# Generated by Django 6.0.6 on 2026-06-08 03:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0004_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MLCategoryTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ml_training_data', to='budgets.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ml_category_training_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpensePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_year', models.PositiveIntegerField()),
                ('target_month', models.PositiveSmallIntegerField()),
                ('predicted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-target_year', '-target_month', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'target_year', 'target_month'), name='unique_user_prediction_target_year_month'), models.CheckConstraint(condition=models.Q(('target_month__gte', 1), ('target_month__lte', 12)), name='prediction_month_between_1_and_12'), models.CheckConstraint(condition=models.Q(('predicted_amount__gte', 0)), name='prediction_amount_gte_0')],
            },
        ),
    ]
