# Generated by Django 6.0.6 on 2026-06-26 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0005_mlcategorytrainingdata_expenseprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionrecord',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
