# Generated by Django 6.0.6 on 2026-07-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0006_transactionrecord_receipt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionrecord',
            name='receipt_image',
        ),
    ]
